name: alrayan_admin
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  dio: ^5.3.0
  shared_preferences: ^2.0.15
  loading_indicator: ^3.1.0
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.1
  flutter_svg: ^2.0.7
  email_validator: ^3.0.0
  go_router: ^16.1.0
  get_it: ^8.2.0
  pinput: ^5.0.0
  file_picker:
  image_picker: ^1.0.5
  cached_network_image: ^3.3.0
  internet_connection_checker: ^3.0.1
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  pin_code_fields:
  intl_phone_field: ^3.2.0
  dartz: ^0.10.1
  fluttertoast: ^8.2.12
  timer_count_down: ^2.2.2
  carousel_slider: ^5.0.0
  readmore: ^3.0.0
  dotted_line: ^3.2.2
  skeletonizer:
  flutter_launcher_icons: ^0.14.2
  firebase_messaging: ^16.0.0
  firebase_core: ^4.0.0
  url_launcher: ^6.3.1
  package_info_plus:
  coupon_uikit: ^0.2.1
  onesignal_flutter: ^5.3.2
  flutter_animate: ^4.5.2
  badges: ^3.1.2
  cherry_toast: ^1.13.0
  google_maps_flutter: ^2.12.3
  geocoding: ^4.0.0
  geolocator:
  google_places_flutter: ^2.1.0
  lottie:
  pretty_dio_logger:
  flutter_spinkit: ^5.2.1
  pie_chart: ^5.3.2




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/account_icons/
    - assets/images/coupons_icons/
    - assets/images/admin_home/
    - lib/core/language/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Cairo.ttf
